### ISSUE TITLE
elapsed time reports are erroneous

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/reconstruct-order#92]
**Bug**
Elapsed time is erroneous. It doesn't take 10hrs to write data

**To Reproduce**
Analyze a 122 slice z-stack. This is a config. 

`/gpfs/CompMicro/Projects/learningCellState/HAE/SMS_2020_0608_1732_4_SMS_2020_0608_1732_4/config.yml`

**Screenshots**
![image](https://user-images.githubusercontent.com/2934183/92145305-e0de5580-edcc-11ea-8390-dc4b435f6af1.png)

**Comment by camFoltz** [comment]
Fixed in compute_new_schemes branch.  Error resides in a missing '/ 60 ' in multiDimProcess.py line 491
